### ISSUE TITLE
Update Notification Does not disappear

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/License-Manager#100]
### What did you expect to happen?
The "Yoast SEO has been updated to version 3.4.2. Find out what's new!" would disappear when clicked
### What happened instead?
The text became lighter but then still remained
### How can we reproduce this behavior?
**1.Go to SEO->Dashboard and see notification**

**2.Click on "x" to remove it**

![1](https://cloud.githubusercontent.com/assets/8238074/21365266/b290b3d8-c6c2-11e6-9466-525fdbb135e3.png)

**3.See screen become lighter**

![2](https://cloud.githubusercontent.com/assets/8238074/21365287/c2e89fe8-c6c2-11e6-8618-b63948d77f51.png)

**4.See message remain**
![3](https://cloud.githubusercontent.com/assets/8238074/21365288/c46498e0-c6c2-11e6-9d9b-24c2b1a5cc12.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.7
* Yoast SEO version: 4.0.2

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/License-Manager/issues/99

**Comment by mazedulislamkhan** [comment]
This issue was fixed in the Yoast SEO v4.0. See here: https://github.com/Yoast/wordpress-seo/issues/5862. If the issue still occurs, you may want to move this issue to the SEO repository

**Comment by atimmer** [comment]
Duplicates #99
