### ISSUE TITLE
Yoast SEO Premium 5.3.1 When License is Inactive A Warning Message Shows up in the Dashboard and the License Field Becomes Empty

### ISSUE THREAD

**Issue by Jerparx** [Yoast/License-Manager#118]
### Please give us a description of what happened.
A notification under Problems section says "You are not receiving updates or support! Fix this problem by adding this site and enabling Yoast SEO Premium for it in [My Yoast](https://yoast.com/#utm_source=yoast_seo&utm_medium=textlink&utm_campaign=notification-local-seo)." shows up after updating the plugin to Yoast SEO Premium 5.3.1
![image](https://user-images.githubusercontent.com/28541738/29581427-cd0efd32-87ab-11e7-804a-8088de56a80d.png)

This message shows up when the license is inactive. It also clears the inactive license field.
![image](https://user-images.githubusercontent.com/28541738/29581357-9a4ea1ae-87ab-11e7-8bc1-75a594451b7a.png)

### Please describe what you expected to happen and why.
Should have a clear notification on what the customer should do like "Activate your license under License section".
It should not empty the license field of the inactive plugins.

### How can we reproduce this behavior?
1. Installed Yoast SEO Premium 5.3.1
2. Deactivate license under SEO → Premium (Extensions in older versions) → Licenses
3. Go to Dashboard and check under Problems section. The notification should appear.
4. Click on My Yoast and it should redirect you to https://yoast.com/#utm_source=yoast_seo&utm_medium=textlink&utm_campaign=notification-local-seo
5. Go back to Premium > Licenses
6. You should notice the field of the inactive plugin now blank when you click on the field.

### Technical info
* WordPress version: 4.8.1
* Yoast SEO version: 5.3.1

**Comment by Jerparx** [comment]
Please inform the customer of conversation # 216945 when this conversation has been closed.

**Comment by Jerparx** [comment]
Please inform the customer of conversation # 216987 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 217029 when this conversation has been closed.

**Comment by atimmer** [comment]
Closed in https://github.com/Yoast/wordpress-seo/pull/7752
