### ISSUE TITLE
Activation problem on multi-sites

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/License-Manager#58]
**Network admin shows activated extension**
![yoast_google_analytics__general_settings_ _network_admin__the_fun_times_guide_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/5523883/7e2b1760-89ce-11e4-8d88-e0c221439dcb.png)

**Admin of subsite shows inactive license**
![yoast_google_analytics__extensions_ _living_green_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/5523857/28ee4074-89ce-11e4-9ccc-ea5d8f5e6905.png)

**When going back to Network admin, it shows a deactivated license**
![yoast_google_analytics__general_settings_ _network_admin__the_fun_times_guide_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/5523938/480add68-89cf-11e4-840b-2c21d9ec0f79.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 90872 when this issue has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 109848 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 114970 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 116511 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120470 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 128432 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 116511 when this conversation has been closed.

**Comment by atimmer** [comment]
When solving this you could also address #70. Take a look at how this is solved in #73.
