### ISSUE TITLE
Maintain Consistency in Function Calls

### ISSUE THREAD

**Issue by amboutwe** [Yoast/License-Manager#70]
class-license-manager.php at line [261](https://github.com/Yoast/License-Manager/blob/master/class-license-manager.php#L261) uses the function get_option( 'home' )

class-update-manager.php at line [118](https://github.com/Yoast/License-Manager/blob/master/class-update-manager.php#L118) use the function home_url().

While these typically return the same value, it may cause problems for installs that return different values.

**Comment by t-ionut** [comment]
In the case of installs with wp-admin on a separate domain from public site, which domain should be the one on which Yoast SEO registers the license?

**Comment by t-ionut** [comment]
Proposed fix in https://github.com/Yoast/License-Manager/pull/71

**Comment by moorscode** [comment]
This will be fixed in #117
