### ISSUE TITLE
Plugin gone after update

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/License-Manager#78]
**Problem description**
We've received a couple of reports of plugins that suddenly disappear after upgrading. 
![_115622_re__yoast_woocommerce_seo_update__-_simon_egle](https://cloud.githubusercontent.com/assets/5147598/14817305/a5eb67c6-0bb6-11e6-96b3-9a09d21b3762.png)

**Possible cause**
So far, we haven't been able to reproduce it or find common denominators between occurences.

**Next steps**
In this issue, we want to collect data about the different occurences, so we can find what's causing this. When encountering this problem, please report the following:

* Plugin showing this behaviour
* Previous plugin version
* Plugin version customer tried to upgrade to
* PHP version
* Web server's OS 
* Web server (Apache / NGINX)
* Any other possibly relevant details
* Name of the web host

[ UPDATED: Added name of web host to 'checklist' ]

**Comment by tacoverdo** [comment]
**Plugin showing this behaviour**
Yoast WooCommerce SEO

**Previous plugin version**
3.1.x (unknown)

**Plugin version customer tried to upgrade to**
3.2

**PHP version**
5.6

**OS**
Linux

**Web server (Apache / NGINX)**
Unknown

Please inform the customer of conversation # 115622 when this conversation has been closed.

**Comment by amboutwe** [comment]
**Plugin**: Local SEO
**Previous version**: 3.2.1
**Upgrade version**: 3.2.2 (invalid)

**Plugin**: Video SEO
**Previous version**: 3.2
**Upgrade version**: 3.2.2 (invalid)

## Server Details ##
**PHP version**: Unknown
**Server OS**: Unknown
**Apache / NGINX**: NGINX
**Webhost**: WP Engine

[User submitted video](https://www.youtube.com/watch?v=k4eJyGH083w)

Please inform the customer of conversation # 115825 when this conversation has been closed.

**Comment by amboutwe** [comment]
After installing the current version, a notification shows saying 'Yoast SEO has been updated'. Why does a Yoast SEO notification show when installing Local SEO, Video SEO or WooCom SEO?

**Plugin**: Local SEO
**Previous version**: 3.2.1
**Upgrade version**: 3.2.2 (invalid)

**Plugin**: Video SEO
**Previous version**: 3.2
**Upgrade version**: 3.2.2 (invalid)

**Plugin**: WooCom SEO
**Previous version**: 3.2
**Upgrade version**: 3.2.2 (invalid)

## WordPress Details ##
**WordPress**: 4.5.1
**Theme**: Genesis child theme

## Server Details ##
**PHP version**: 5.2.17
**Server OS**: Linux
**Apache / NGINX**: NGINX
**Webhost**: BlueHost

Please inform the customer of conversation # 112185 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
**Plugin showing this behaviour**
Yoast WooCommerce SEO

**Previous plugin version**
3.2

**Plugin version customer tried to upgrade to**
3.2.1

**PHP version**
5.6.19-nmm1

**OS**
Linux

**Web server**
Apache

**Plugin updated method**
WordPress admin and FTP

**cURL version**
7.35.0

**WordPress version**
4.5

Please inform the customer of conversation 115622 when this conversation has been closed.

**Comment by tacoverdo** [comment]
**Plugin showing this behaviour**
Yoast WooCommerce SEO

**Previous plugin version**
3.2

**Plugin version customer tried to upgrade to**
3.2.1

**PHP version**
PHP Version: 5.6.18
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: -
MySQL Version: 5.5.5
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Web server (Apache / NGINX)**
Apache

Please inform the customer of conversation # 115871 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
**Plugin showing this behaviour**
Local SEO

**Previous plugin version**
1.3.8

**Plugin version customer tried to upgrade to**
3.2.1

**PHP version**
5.4.42

**OS**
Linux RHEL

**Web server**
Apache

**Plugin updated method**
WordPress admin

Please inform the customer of conversation 117028 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
**Plugin showing this behaviour**
Local SEO

**Previous plugin version**
3.x (unknown)

**Plugin version customer tried to upgrade to**
3.2.1

**PHP version**
5.4.42

**OS**
Linux (Distro unknown)

**cURL version**
7.45.0

**Web server**
Apache

Please inform the customer of conversation 115635 when this conversation has been closed.

**Comment by sugrbug** [comment]
Plugin showing this behavior: **Local** SEO 
Current plugin version: Version 3.2.1
Plugin version customer tried to upgrade to: The next one
PHP version: 5.5.33
Web server's OS: Linux
Web server (Apache / NGINX): Apache/2.4.12
Any other possibly relevant details
Name of the web host: GoDaddy.com

**Comment by sugrbug** [comment]
Plugin showing this behavior: **Video** SEO 
Current plugin version: Version 3.2
Plugin version customer tried to upgrade to: The next one
PHP version: 5.5.33
Web server's OS: Linux
Web server (Apache / NGINX): Apache/2.4.12
Any other possibly relevant details
Name of the web host: GoDaddy.com

**Comment by krisfannin** [comment]
One thing I have noticed is I get random email notifications with the old license after retrieving the new. It's almost as though it reverts back. We upgraded from single to multisite.

**Comment by amboutwe** [comment]
@krisfanninThe [license retrieval form](https://yoast.com/licenses/) sends you a copy of all completed purchase receipts not just active licenses.

**Comment by Pcosta88** [comment]
Plugin showing this behavior: Local SEO
Current plugin version: Version 3.2.1
Plugin version customer tried to upgrade to: The next one
PHP version: PHP Version 5.5.9-1ubuntu4.16
Web server's OS: Linux
Web server (Apache / NGINX): n/a
Any other possibly relevant details: See also[ PHP Environment](http://phpinfo.wpengine.com/)
Name of the web host: WPengine
Please inform the customer of conversation # 115828 when this conversation has been closed.

**Comment by krisfannin** [comment]
So I assume we still should not update on any site?

[image: photo]
*Kris Fannin*
CEO & Founder, Intelivate
813-337-6363 | kris.fannin@intelivate.com
<http://twitter.com/krisfannin>  <http://www.linkedin.com/in/krisfannin>
<http://www.facebook.com/intelivate>  <http://instagram.com/kris.fannin>
<http://plus.google.com/+KristopherFannin>
<http://www.youtube.com/user/intelivateinc>
<http://www.intelivate.com/feed>  <http://google.com/search?q=kris fannin>
<http://www.intelivate.com>
Wealth of Self Love Your Career and Always Laugh
<https://www.intelivate.com/inspire-idea/love-career-always-laugh>

On Mon, May 2, 2016 at 6:04 PM Pat Costa <notifications@github.com> wrote:

> Plugin showing this behavior: Local SEO
> Current plugin version: Version 3.2.1
> Plugin version customer tried to upgrade to: The next one
> PHP version: PHP Version 5.5.9-1ubuntu4.16
> Web server's OS: Linux
> Web server (Apache / NGINX): n/a
> Any other possibly relevant details: See also PHP Environment
> <http://phpinfo.wpengine.com/>
> Name of the web host: WPengine
> Please inform the customer of conversation # 115828 when this conversation
> has been closed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Yoast/License-Manager/issues/78#issuecomment-216379395>
>
-- 
Kris Fannin
CEO and Founder
Intelivate

-- 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. E-mail transmission cannot be 
guaranteed to be secure or error-free as information could be intercepted, 
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. 
The sender therefore does not accept liability for any errors or omissions 
in the contents of this message, which arise as a result of e-mail 
transmission.

**Comment by monbauza** [comment]
Plugin: Local SEO and WooCommerce SEO
Previous version: 3.2.1
Upgrade version: 3.2.4 (invalid)
Plugin update method (FTP/WordPress admin): Both

**WordPress Details**

WordPress: 4.5.1
Yoast SEO Premium 3.2.4
Theme: Porto ChildVersion: 1.1 By SW-THEMES

**Server Details**

PHP version : 5.6.14
Web server's OS : linux x86_64
Web server (Apache / NGINX) : Apache 2.2.29
Cloudflare

Please inform the customer of conversation # 115979 when this conversation has been closed.

**Comment by monbauza** [comment]
Plugin: Local SEO and Video SEO
Previous version: Unknown
Upgrade version: Unknown
Plugin update method (FTP/WordPress admin): Admin

**Server Details**

PHP version : 5.5
Web server's OS: Ubuntu Linux 
Web server (Apache / NGINX) : Apache 2.2.31

Please inform the customer of conversation # 115818 when this conversation has been closed.

**Comment by amboutwe** [comment]
**Plugin**: Local SEO
**Previous version**: 3.2.1
**Upgrade version**: 3.2.4 (invalid)

## Server Details ##
**PHP version**: 5.6.18
**Server OS**: Unknown
**Web Server**: LiteSpeed
**Webhost**: Unknown

Please inform the customer of conversation # 117382 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
**Plugin showing this behaviour**
Local SEO

**Previous plugin version**
3.x (unknown)

**Plugin version customer tried to upgrade to**
3.2.1

**PHP version**
5.3.26

**OS**
Linux (Distro unknown)

**Web server**
Apache Version 2.2.24

**Plugin updated method**
WordPress admin and FTP

**Name of the Webhost**
Siteground

Please inform the customer of conversation # 116338 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 116606 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 119163 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 119769 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 119235 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120105 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120221 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120227 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120228 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120318 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120394 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120400 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120399 when this conversation has been closed.

**Comment by monbauza** [comment]
I am not sure if it is related but a customer has received the warnings below after trying to update Local SEO from 3.2.1 to 3.2.5
After the update, the plugin is deleted like other customers have reported
![image](https://cloud.githubusercontent.com/assets/9658774/15322457/51aa0e46-1c3d-11e6-8bb3-55f5499061ed.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120645 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120587 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120711 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120864 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120892 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121554 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121657 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121782 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121745 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121941 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 121675 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122135 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 118957 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122784 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122782 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122773 when this conversation has been closed.

**Comment by RAMINCNZ** [comment]
Hi there

Thought I would chime in and advise, I just deactivated Licences for Local SEO and Yoast SEO.. When I deactivated Local SEO the alleged update to 3.2.5 disappeared from the Updates Page.. I have already been added to the list to be advised when a solution has been found..

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122854 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 122795 when this conversation has been closed.

**Comment by krisfannin** [comment]
Is this still not fixed?

**Comment by combra** [comment]
Plugin: Woocommerce SEO
Previous version: 3.2.1
Upgrade version: 3.2.5 (invalid)

Plugin: Yoast SEO (Premium)
Previous version: 3.2.1
Upgrade version: 3.2.5 (invalid)

-> Only Woocommerce SEO gone after updating to lastest version (like screenshot on first post)

Server Details

PHP version: 5.5.35
MySQL version 5.6.30
Apache
Webhost: all-inkl.com

**Comment by monbauza** [comment]
Please inform the customer of conversation # 123297 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 123188 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123444 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123523 when this conversation has been closed.

**Comment by combra** [comment]
![image](https://cloud.githubusercontent.com/assets/19666012/15772058/311efe54-296f-11e6-9607-8b34ed56dd64.png)

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123913 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123928 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124580 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 124884 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 124944 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 125326 when this conversation has been closed.

**Comment by tklopp** [comment]
What is the latest on resolving this problem. We are going on 3 months with this? Will there be an extension of subscriptions for those affected by this problem?

**Comment by krisfannin** [comment]
I'd like to know this as well. Haven't been able to update either of them
on 3 sites.

On Tue, Jun 14, 2016, 10:16 AM tklopp <notifications@github.com> wrote:

> What is the latest on resolving this problem. We are going on 3 months
> with this? Will there be an extension of subscriptions for those affected
> by this problem?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Yoast/License-Manager/issues/78#issuecomment-225894883>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALYW5mD4CwNgxD95L9clZVqNRCNVl_8Kks5qLrexgaJpZM4IP4EU>
> .
>
-- 
Kris Fannin
CEO and Founder
Intelivate

-- 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. E-mail transmission cannot be 
guaranteed to be secure or error-free as information could be intercepted, 
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. 
The sender therefore does not accept liability for any errors or omissions 
in the contents of this message, which arise as a result of e-mail 
transmission.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124835 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 126659 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 118955 when this conversation has been closed.

**Comment by atimmer** [comment]
If all plugins running on a certain site have included version 1.3 of the license manager this is fixed.

**Comment by tacoverdo** [comment]
Which plugins are using this license manager and how/where can we see if they're using version 1.3?

**Comment by atimmer** [comment]
There is no great way to easily find out which plugins use the license manager. [Yoast SEO](https://github.com/Yoast/wordpress-seo/) includes version 1.3 since 3.3. The [Google Analytics by MonsterInsights](https://wordpress.org/plugins/google-analytics-for-wordpress/) also includes the license manager but I have no idea in which version they included 1.3.
