### ISSUE TITLE
Missing or Invalid Update Notifications For Add-ons

### ISSUE THREAD

**Issue by amboutwe** [Yoast/License-Manager#79]
A prompt to update to an invalid version might be causing the disappearing plugin ( #78 ). Screenshots from my test environment with only Yoast plugins installed.

Yoast SEO Free With Add-ons Active
![selection_134](https://cloud.githubusercontent.com/assets/8060612/14893518/05e4c54c-0d2d-11e6-968b-66716ce06d34.png)

Yoast SEO Premium With All Add-ons Active
![selection_135](https://cloud.githubusercontent.com/assets/8060612/14893482/de8fc0e6-0d2c-11e6-9090-92ee3a9f59ff.png)

Yoast SEO Premium With All Add-ons (Except News SEO) Active
![selection_136](https://cloud.githubusercontent.com/assets/8060612/14893568/2a64a84c-0d2d-11e6-9512-b88add18b035.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 117216 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 117246 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 116455 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 117290 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation `116455` when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation `117385` when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation `115751` when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation `117213` when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 117693 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 116033 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118126 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 117422 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 115026 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 117533 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation #  115741 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118376 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118440 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118959 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118904 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118884 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 118998 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 116153 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 117406 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 116606 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 117450 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 119337 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 119586 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 118992 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120221 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120227 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120228 when this conversation has been closed.

**Comment by moorscode** [comment]
We have changed the 'slug' part of the license managing to fix the inline updating functionality in WordPress core.

See https://github.com/Yoast/License-Manager/pull/77

Thus the products have been updated to reflect this and now supply a `slug` and `file` parameter to the License Manager. Though only the updated License manager can handle this information.

_Untested/unconfirmed thesis_
The problem lies in the fact that the `slug` has not been kept backwards compatible and has been changed to `dirname( $slug )`.

With multiple products containing (a version of) the License Manager, everything will work as expected when the newest version of the License Manager is in the plugin which is loaded first. Otherwise an older version of the Manager is loaded which is causing problems.

@omarreiss @atimmer @moorscode session is required to come up with a solution.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120318 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 116044 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 116187 when this conversation has been closed.
User reports wrong-update count which triggers WordFence update notifications.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120399 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 119792 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120711 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120791 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120864 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121265 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121245 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121312 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121355 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121657 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121630 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121745 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120358 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121941 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122135 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 122175 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 122526 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 120525 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 122645 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 122795 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 122921 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 123297 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 123188 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123469 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123460 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123774 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124001 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123444 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124104 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124098 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124275 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124273 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124580 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124655 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 124704 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124243 when this conversation has been closed.
User reports that when he clicks to update the "An error occurred while updating Local SEO for Yoast SEO: Download failed. Unauthorized" appears.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 124884 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123550 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 121782 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124861 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 125326 when this conversation has been closed.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 125561 when this conversation has been closed.
