### ISSUE TITLE
Invalid Update Now and New Version Message when Google Analytics by Monster Insights is Active

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/License-Manager#80]
- When Google Analytics (GA) by Monster Insights (MI) is active and Yoast SEO Premium is active a message appears in Yoast SEO that an update is available. 
- When GA is deactivated and Yoast SEO Premium is active, Yoast SEO Premium becomes highlighted without an "update now" message in the plugin screen, suggesting an update is available.
- When GA is reactivated and Yoast SEO Premium is active, Yoast SEO Premium is highlighted with an "update now message".

Yoast SEO, during the deactivation/reactivation of GA, neither was highlighted nor displayed an "update now" message.

Monster Insights is aware of the issue.

**Steps to Reproduce:**

1. GA and Yoast SEO Active
 ![yoast seo premium with ma](https://cloud.githubusercontent.com/assets/8238074/15188219/9187262c-1772-11e6-9b7f-956747bc29fa.jpg)

4.  Deactivate GA
![gabymi](https://cloud.githubusercontent.com/assets/8238074/15188350/3da848fa-1773-11e6-9b2d-68a30c829b66.jpg)

8. Reactivate GA
 ![screen shot 2016-05-06 at 5 39 13 pm](https://cloud.githubusercontent.com/assets/8238074/15188256/acddf306-1772-11e6-933c-6623852ec8a0.png)

**Technical**
WordPress: 4.5.2
Yoast SEO: 3.2.4
Yoast SEO Premium: 3.2.4
GA by MI: 5.5

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 115752 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 124884 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 126348 when this conversation has been closed.

**Comment by omarreiss** [comment]
If I am not mistaken, this bug was fixed in a recent update of monster insights. @moorscode could you confirm and close this issue if that's indeed the case?

**Comment by moorscode** [comment]
This relates to the License Manager problems we had between 3.2 and 3.3. Monster Insights has updated the License Manager in their latest release, fixing this problem indeed.

So users should disable any of the two plugins and update each one to the latest version to restore expected behaviour.
