### ISSUE TITLE
License Activation Fails

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/License-Manager#85]
A correctly generated license fails to activate. It results in the message, "Failed to activate your license, your license key seems to be invalid." The message is happening on both multisites and single sites. It happens with old and new licenses. 

**Plugins affected:**
Yoast SEO Premium 
News SEO
Yoast Complete SEO

Image taken from my development site
![failed activation](https://cloud.githubusercontent.com/assets/8238074/15903574/619f481c-2d7b-11e6-9f4a-9e09351e4212.jpg)

**Tech Specs:**
WordPress: 4.5.2 
Yoast SEO Premium: 3.5.2

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124838 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124840 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124796 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124836 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124805 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124833 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124812 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124829 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124828 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124806 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124822 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124820 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124814 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124809 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124818 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124815 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124817 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124843 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124844 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124847 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124845 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124850 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124853 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124803 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124856 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 124835 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 124863 when this conversation has been closed.
