### ISSUE TITLE
[Feature Request] Provide ability of license to be used on just a production and staging site / development site

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/License-Manager#93]
Users who push from the development to the production site need to deactivate licenses each time they want to update one site or the other. We should provide the ability of a license to be used strictly on a production site and its accompanying development site.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation #156670 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 159188 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 160894 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 165222 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 163406 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 174394 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 179595 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/License-Manager/issues/115

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 212568 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 211131 when this conversation has been closed.

**Comment by jdevalk** [comment]
I think we've solved this in MyYoast? @moorscode ?

**Comment by moorscode** [comment]
As the license is now based on the URL, the plugin would automatically be activated for the site when accessed there.
