### ISSUE TITLE
Incorrect Update Notification 

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/License-Manager#99]
### What did you expect to happen?
It would say 4.0.2 after updating
### What happened instead?
It said "Yoast SEO has been updated to version 3.4.2. Find out what's new!"
### How can we reproduce this behavior?
**1. Install Yoast SEO 4.0.1**

![1](https://cloud.githubusercontent.com/assets/8238074/21365108/cbecc714-c6c1-11e6-863c-3af3da01250a.png)

**2. Update to 4.0.2** 
![screen shot 2016-12-20 at 2 37 24 pm](https://cloud.githubusercontent.com/assets/8238074/21365120/db7f87de-c6c1-11e6-911e-ada7b25441a0.png)
via the plugins menu

**3. See Yoast SEO has been updated to version 3.4.2. Find out what's new!" appears in the SEO->Dashboard**

![screen_shot_2016-12-20_at_2_38_05_pm](https://cloud.githubusercontent.com/assets/8238074/21365157/09ec6b32-c6c2-11e6-9a55-6cd72dae7010.png)

Can you provide a link to a page which shows this issue? n/a

### Technical info
* WordPress version: 4.7
* Yoast SEO version: 4.0.1 to 4.0.2
Note: When plugin was active on 4.0.1, notices for 3.4.2 were appearing in the Dashboard.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 166347 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
This issue was fixed in the Yoast SEO v4.0. See here: https://github.com/Yoast/wordpress-seo/issues/5862
